import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { endpointApi } from '../api';
import { formatBeijingDateTime } from '../utils/timeUtils';
import './EndpointList.css';

function EndpointList() {
  const [endpoints, setEndpoints] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [searchInput, setSearchInput] = useState('');
  const [expandedDoc, setExpandedDoc] = useState(null);
  const [pagination, setPagination] = useState({
    page: 1,
    limit: 12,
    total: 0,
    totalPages: 0
  });

  const fetchEndpoints = useCallback(async () => {
    setLoading(true);
    try {
      const response = await endpointApi.getAll({
        search,
        page: pagination.page,
        limit: pagination.limit
      });
      setEndpoints(response.data.data || []);
      setPagination(prev => ({
        ...prev,
        ...response.data.pagination
      }));
    } catch (error) {
      console.error('Failed to fetch endpoints:', error);
      setEndpoints([]);
    } finally {
      setLoading(false);
    }
  }, [search, pagination.page, pagination.limit]);

  useEffect(() => {
    fetchEndpoints();
  }, [fetchEndpoints]);

  const handleSearch = (e) => {
    e.preventDefault();
    setSearch(searchInput);
    setPagination(prev => ({ ...prev, page: 1 }));
  };

  const handlePageChange = (newPage) => {
    if (newPage >= 1 && newPage <= pagination.totalPages) {
      setPagination(prev => ({ ...prev, page: newPage }));
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const getVisibilityLabel = (visibility) => {
    const labels = {
      public: '公开',
      restricted: '受限',
      private: '私有'
    };
    return labels[visibility] || '公开';
  };

  const copyApiUrl = (name) => {
    const url = `${window.location.origin}/endpoints/run/${name}`;
    navigator.clipboard.writeText(url);
    alert('API 地址已复制到剪贴板');
  };

  const toggleDoc = (id) => {
    setExpandedDoc(expandedDoc === id ? null : id);
  };

  const parseMetadata = (metadataStr, code) => {
    let metadata = { params: [], description: '', response: { example: {} } };

    try {
      if (metadataStr) {
        const parsed = typeof metadataStr === 'string' ? JSON.parse(metadataStr) : metadataStr;
        metadata = {
          params: parsed.params || [],
          description: parsed.description || '',
          response: parsed.response || { example: {} }
        };
      }
    } catch (e) {
      // ignore parse error
    }

    // 如果没有手动配置参数，从代码中自动提取
    if ((!metadata.params || metadata.params.length === 0) && code) {
      const extractedParams = extractParamsFromCode(code);
      if (extractedParams.length > 0) {
        metadata.params = extractedParams;
        metadata.autoGenerated = true;
      }
    }

    return metadata;
  };

  // 从代码中提取 params.get 调用
  const extractParamsFromCode = (code) => {
    const params = [];
    const seen = new Set();

    // 匹配 params.get('name', default) 或 params.get("name", default) 或 params['name']
    const patterns = [
      /params\.get\s*\(\s*['"]([^'"]+)['"]\s*(?:,\s*([^)]+))?\)/g,
      /params\s*\[\s*['"]([^'"]+)['"]\s*\]/g
    ];

    for (const pattern of patterns) {
      let match;
      while ((match = pattern.exec(code)) !== null) {
        const paramName = match[1];
        if (!seen.has(paramName)) {
          seen.add(paramName);
          let defaultVal = match[2] ? match[2].trim() : '';
          // 清理默认值
          if (defaultVal.startsWith("'") || defaultVal.startsWith('"')) {
            defaultVal = defaultVal.slice(1, -1);
          }

          // 推断类型
          let type = 'string';
          if (defaultVal === 'True' || defaultVal === 'False' || defaultVal === 'true' || defaultVal === 'false') {
            type = 'boolean';
          } else if (/^\d+$/.test(defaultVal)) {
            type = 'number';
          } else if (/^\d+\.\d+$/.test(defaultVal)) {
            type = 'number';
          }

          params.push({
            name: paramName,
            type: type,
            required: false,
            default: defaultVal,
            description: '自动提取'
          });
        }
      }
    }

    return params;
  };

  const generateCurlExample = (name, metadata) => {
    const baseUrl = `${window.location.origin}/endpoints/run/${name}`;
    if (!metadata?.params?.length) {
      return `curl "${baseUrl}"`;
    }
    const params = metadata.params
      .filter(p => p.name)
      .map(p => `${p.name}=${p.default || `<${p.type}>`}`)
      .join('&');
    return `curl "${baseUrl}?${params}"`;
  };

  const generateJsExample = (name, metadata) => {
    const baseUrl = `/endpoints/run/${name}`;
    if (!metadata?.params?.length) {
      return `fetch('${baseUrl}')
  .then(res => res.json())
  .then(data => console.log(data));`;
    }
    const paramsObj = {};
    metadata.params.filter(p => p.name).forEach(p => {
      paramsObj[p.name] = p.default || `<${p.type}>`;
    });
    return `fetch('${baseUrl}', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify(${JSON.stringify(paramsObj, null, 2)})
})
  .then(res => res.json())
  .then(data => console.log(data));`;
  };

  const generatePythonExample = (name, metadata) => {
    const baseUrl = `${window.location.origin}/endpoints/run/${name}`;
    if (!metadata?.params?.length) {
      return `import requests

response = requests.get('${baseUrl}')
print(response.json())`;
    }
    const paramsObj = {};
    metadata.params.filter(p => p.name).forEach(p => {
      paramsObj[p.name] = p.default || `<${p.type}>`;
    });
    return `import requests

response = requests.post('${baseUrl}', json=${JSON.stringify(paramsObj)})
print(response.json())`;
  };

  return (
    <div className="endpoint-list-page">
      <div className="container">
        <div className="page-header">
          <div className="header-content">
            <h1>端口列表</h1>
            <p className="page-description">
              浏览所有公开的端口，可以直接调用获取动态内容
            </p>
          </div>
        </div>

        {/* 搜索栏 */}
        <div className="search-section">
          <form onSubmit={handleSearch} className="search-form">
            <div className="search-input-wrapper">
              <svg className="search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="11" cy="11" r="8"/>
                <path d="m21 21-4.35-4.35"/>
              </svg>
              <input
                type="text"
                placeholder="搜索端口名称、描述或创建者..."
                value={searchInput}
                onChange={(e) => setSearchInput(e.target.value)}
                className="search-input"
              />
              {searchInput && (
                <button
                  type="button"
                  className="clear-btn"
                  onClick={() => {
                    setSearchInput('');
                    setSearch('');
                    setPagination(prev => ({ ...prev, page: 1 }));
                  }}
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M18 6L6 18M6 6l12 12"/>
                  </svg>
                </button>
              )}
            </div>
            <button type="submit" className="btn btn-primary">搜索</button>
          </form>
          {search && (
            <div className="search-result-info">
              搜索 "{search}" 找到 {pagination.total} 个结果
            </div>
          )}
        </div>

        {/* 端口列表 */}
        {loading ? (
          <div className="loading-state">
            <div className="loading-spinner"></div>
            <p>加载中...</p>
          </div>
        ) : endpoints.length === 0 ? (
          <div className="empty-state">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <path d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/>
            </svg>
            <h3>暂无端口</h3>
            <p>{search ? '没有找到匹配的端口，请尝试其他关键词' : '还没有公开的端口'}</p>
          </div>
        ) : (
          <>
            <div className="endpoint-grid">
              {endpoints.map((endpoint) => {
                const metadata = parseMetadata(endpoint.metadata, endpoint.code);
                return (
                <div key={endpoint.id} className={`endpoint-card ${expandedDoc === endpoint.id ? 'expanded' : ''}`}>
                  <div className="card-header">
                    <h3 className="endpoint-name">{endpoint.name}</h3>
                    <span className={`visibility-badge visibility-${endpoint.visibility || 'public'}`}>
                      {getVisibilityLabel(endpoint.visibility)}
                    </span>
                  </div>
                  <p className="endpoint-desc">
                    {endpoint.description || '暂无描述'}
                  </p>
                  <div className="endpoint-meta">
                    <span className="meta-item">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/>
                        <circle cx="12" cy="7" r="4"/>
                      </svg>
                      {endpoint.username}
                    </span>
                    <span className="meta-item">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>
                      </svg>
                      {endpoint.call_count || 0} 次调用
                    </span>
                  </div>
                  <div className="endpoint-footer">
                    <span className="created-date">
                      {formatBeijingDateTime(endpoint.created_at)}
                    </span>
                    <div className="card-actions">
                      <button
                        onClick={() => toggleDoc(endpoint.id)}
                        className="btn btn-sm btn-outline"
                      >
                        {expandedDoc === endpoint.id ? '收起' : '文档'}
                      </button>
                      <button
                        onClick={() => copyApiUrl(endpoint.name)}
                        className="btn btn-sm btn-secondary"
                      >
                        复制
                      </button>
                    </div>
                  </div>

                  {/* API 文档展开区域 */}
                  {expandedDoc === endpoint.id && (
                    <div className="api-doc-panel">
                      <div className="doc-section">
                        <h4>API 地址</h4>
                        <code className="api-url">{`${window.location.origin}/endpoints/run/${endpoint.name}`}</code>
                        <div className="method-badges">
                          <span className="method-badge get">GET</span>
                          <span className="method-badge post">POST</span>
                        </div>
                      </div>

                      {metadata.description && (
                        <div className="doc-section">
                          <h4>说明</h4>
                          <p>{metadata.description}</p>
                        </div>
                      )}

                      {metadata.params && metadata.params.length > 0 && (
                        <div className="doc-section">
                          <h4>
                            参数
                            {metadata.autoGenerated && <span className="auto-tag">自动识别</span>}
                          </h4>
                          <table className="doc-params-table">
                            <thead>
                              <tr>
                                <th>参数名</th>
                                <th>类型</th>
                                <th>必填</th>
                                <th>默认值</th>
                                <th>说明</th>
                              </tr>
                            </thead>
                            <tbody>
                              {metadata.params.filter(p => p.name).map((param, idx) => (
                                <tr key={idx}>
                                  <td><code>{param.name}</code></td>
                                  <td>{param.type}</td>
                                  <td>{param.required ? '是' : '否'}</td>
                                  <td>{param.default || '-'}</td>
                                  <td>{param.description || '-'}</td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      )}

                      {metadata.response?.example && (
                        <div className="doc-section">
                          <h4>响应示例</h4>
                          <pre className="response-example">
                            {typeof metadata.response.example === 'object'
                              ? JSON.stringify(metadata.response.example, null, 2)
                              : metadata.response.example}
                          </pre>
                        </div>
                      )}

                      <div className="doc-section">
                        <h4>调用示例</h4>
                        <div className="code-examples">
                          <div className="code-example">
                            <h5>cURL</h5>
                            <pre>{generateCurlExample(endpoint.name, metadata)}</pre>
                          </div>
                          <div className="code-example">
                            <h5>JavaScript</h5>
                            <pre>{generateJsExample(endpoint.name, metadata)}</pre>
                          </div>
                          <div className="code-example">
                            <h5>Python</h5>
                            <pre>{generatePythonExample(endpoint.name, metadata)}</pre>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              )})}
            </div>

            {/* 分页 */}
            {pagination.totalPages > 1 && (
              <div className="pagination">
                <button
                  className="page-btn"
                  onClick={() => handlePageChange(1)}
                  disabled={pagination.page === 1}
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <polyline points="11 17 6 12 11 7"/>
                    <polyline points="18 17 13 12 18 7"/>
                  </svg>
                </button>
                <button
                  className="page-btn"
                  onClick={() => handlePageChange(pagination.page - 1)}
                  disabled={pagination.page === 1}
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <polyline points="15 18 9 12 15 6"/>
                  </svg>
                </button>

                <div className="page-numbers">
                  {Array.from({ length: Math.min(5, pagination.totalPages) }, (_, i) => {
                    let pageNum;
                    if (pagination.totalPages <= 5) {
                      pageNum = i + 1;
                    } else if (pagination.page <= 3) {
                      pageNum = i + 1;
                    } else if (pagination.page >= pagination.totalPages - 2) {
                      pageNum = pagination.totalPages - 4 + i;
                    } else {
                      pageNum = pagination.page - 2 + i;
                    }
                    return (
                      <button
                        key={pageNum}
                        className={`page-num ${pagination.page === pageNum ? 'active' : ''}`}
                        onClick={() => handlePageChange(pageNum)}
                      >
                        {pageNum}
                      </button>
                    );
                  })}
                </div>

                <button
                  className="page-btn"
                  onClick={() => handlePageChange(pagination.page + 1)}
                  disabled={pagination.page === pagination.totalPages}
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <polyline points="9 18 15 12 9 6"/>
                  </svg>
                </button>
                <button
                  className="page-btn"
                  onClick={() => handlePageChange(pagination.totalPages)}
                  disabled={pagination.page === pagination.totalPages}
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <polyline points="13 17 18 12 13 7"/>
                    <polyline points="6 17 11 12 6 7"/>
                  </svg>
                </button>
              </div>
            )}

            <div className="pagination-info">
              第 {pagination.page} 页，共 {pagination.totalPages} 页（{pagination.total} 个端口）
            </div>
          </>
        )}
      </div>
    </div>
  );
}

export default EndpointList;
